name: p910nd-pendle 
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: p910nd print queue 
description: |
  p910nd print queue
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

#apps:
#  p910nd:
#    command: bin/p910nd
    
   
parts:
  p910nd:
    # See 'snapcraft plugins'
    source: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/p910nd/0.97-1build1/p910nd_0.97.orig.tar.bz2
    plugin: make

    
